// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ZZPXgr-gyByMejymd5HFXYTGCno-C3s',
    appId: '1:158133594661:web:c7e66f4b9eb13ae4d6edcc',
    messagingSenderId: '158133594661',
    projectId: 'gitwin-49f05',
    authDomain: 'gitwin-49f05.firebaseapp.com',
    storageBucket: 'gitwin-49f05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu6bAl7ekg41F4K2JecZQPFLbAEW70Wbg',
    appId: '1:158133594661:android:f410d4f50a57d389d6edcc',
    messagingSenderId: '158133594661',
    projectId: 'gitwin-49f05',
    storageBucket: 'gitwin-49f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0FUjhQFVLVDfjD6Z88WP9s_Ct1MkQXM',
    appId: '1:158133594661:ios:07424a27cf9bd110d6edcc',
    messagingSenderId: '158133594661',
    projectId: 'gitwin-49f05',
    storageBucket: 'gitwin-49f05.appspot.com',
    iosClientId: '158133594661-m1eau6lfaqenip69k2ofnlbkr4rc0scv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizAppNadaAshrafMohammad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0FUjhQFVLVDfjD6Z88WP9s_Ct1MkQXM',
    appId: '1:158133594661:ios:07424a27cf9bd110d6edcc',
    messagingSenderId: '158133594661',
    projectId: 'gitwin-49f05',
    storageBucket: 'gitwin-49f05.appspot.com',
    iosClientId: '158133594661-m1eau6lfaqenip69k2ofnlbkr4rc0scv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizAppNadaAshrafMohammad',
  );
}
